/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSimulacao.java
 *
 * Created on Dec 7, 2009, 4:48:46 AM
 */

package br.ufrj.dcc.so20092.fastfood.view;

import br.ufrj.dcc.so20092.fastfood.model.CaixaAtendimento;
import br.ufrj.dcc.so20092.fastfood.model.Cliente;
import br.ufrj.dcc.so20092.fastfood.model.FilaAtendimento;
import br.ufrj.dcc.so20092.fastfood.model.ItemPedido;
import br.ufrj.dcc.so20092.fastfood.model.ItemPedido;
import java.awt.Color;
import java.util.HashSet;

/**
 *
 * @author kaiser
 */
public class PanelSimulacao extends javax.swing.JPanel {

    /** Creates new form PanelSimulacao */
    public PanelSimulacao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        caixaAtendimento0 = new javax.swing.JTextArea();
        clientesRestantes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        caixaAtendimento1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        caixaAtendimento2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        fila1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        fila3 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        fila2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        caixaPagamento0 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        caixaPagamento1 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        caixaPagamento2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        fila4 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        fila5 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        fila6 = new javax.swing.JTextArea();

        caixaAtendimento0.setBackground(new java.awt.Color(0, 255, 0));
        caixaAtendimento0.setColumns(20);
        caixaAtendimento0.setLineWrap(true);
        caixaAtendimento0.setRows(2);
        caixaAtendimento0.setText("Caixa livre");
        caixaAtendimento0.setWrapStyleWord(true);
        jScrollPane9.setViewportView(caixaAtendimento0);

        clientesRestantes.setText("0");

        caixaAtendimento1.setBackground(new java.awt.Color(0, 255, 0));
        caixaAtendimento1.setColumns(20);
        caixaAtendimento1.setLineWrap(true);
        caixaAtendimento1.setRows(2);
        caixaAtendimento1.setText("Caixa livre");
        caixaAtendimento1.setWrapStyleWord(true);
        jScrollPane5.setViewportView(caixaAtendimento1);

        caixaAtendimento2.setBackground(new java.awt.Color(0, 255, 0));
        caixaAtendimento2.setColumns(20);
        caixaAtendimento2.setLineWrap(true);
        caixaAtendimento2.setRows(2);
        caixaAtendimento2.setText("Caixa livre");
        caixaAtendimento2.setWrapStyleWord(true);
        jScrollPane4.setViewportView(caixaAtendimento2);

        jLabel1.setText("Caixa Atendimento 0");

        jLabel2.setText("Caixa Atendimento 1");

        jLabel3.setText("Caixa Atendimento 2");

        jButton1.setText("Adicionar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fila1.setColumns(20);
        fila1.setLineWrap(true);
        fila1.setRows(2);
        fila1.setWrapStyleWord(true);
        jScrollPane6.setViewportView(fila1);

        jLabel4.setText("Fila");

        jLabel5.setText("clientes restantes na fila");

        fila3.setColumns(20);
        fila3.setLineWrap(true);
        fila3.setRows(2);
        fila3.setWrapStyleWord(true);
        jScrollPane8.setViewportView(fila3);

        fila2.setColumns(20);
        fila2.setLineWrap(true);
        fila2.setRows(2);
        fila2.setWrapStyleWord(true);
        jScrollPane7.setViewportView(fila2);

        jLabel6.setText("ATENDIMENTO");

        jLabel7.setText("Caixa Pagamento 0");

        jLabel8.setText("Caixa Pagamento 1");

        jLabel9.setText("Caixa Pagamento 2");

        caixaPagamento0.setBackground(new java.awt.Color(0, 255, 0));
        caixaPagamento0.setColumns(20);
        caixaPagamento0.setLineWrap(true);
        caixaPagamento0.setRows(2);
        caixaPagamento0.setText("Caixa livre");
        caixaPagamento0.setWrapStyleWord(true);
        jScrollPane10.setViewportView(caixaPagamento0);

        caixaPagamento1.setBackground(new java.awt.Color(0, 255, 0));
        caixaPagamento1.setColumns(20);
        caixaPagamento1.setLineWrap(true);
        caixaPagamento1.setRows(2);
        caixaPagamento1.setText("Caixa livre");
        caixaPagamento1.setWrapStyleWord(true);
        jScrollPane11.setViewportView(caixaPagamento1);

        caixaPagamento2.setBackground(new java.awt.Color(0, 255, 0));
        caixaPagamento2.setColumns(20);
        caixaPagamento2.setLineWrap(true);
        caixaPagamento2.setRows(2);
        caixaPagamento2.setText("Caixa livre");
        caixaPagamento2.setWrapStyleWord(true);
        jScrollPane12.setViewportView(caixaPagamento2);

        jLabel10.setText("Fila");

        fila4.setColumns(20);
        fila4.setLineWrap(true);
        fila4.setRows(2);
        fila4.setWrapStyleWord(true);
        jScrollPane13.setViewportView(fila4);

        fila5.setColumns(20);
        fila5.setLineWrap(true);
        fila5.setRows(2);
        fila5.setWrapStyleWord(true);
        jScrollPane14.setViewportView(fila5);

        fila6.setColumns(20);
        fila6.setLineWrap(true);
        fila6.setRows(2);
        fila6.setWrapStyleWord(true);
        jScrollPane15.setViewportView(fila6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(95, 95, 95)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(clientesRestantes)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel4)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clientesRestantes)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atualizarClientes();
        adicionarCliente();
}//GEN-LAST:event_jButton1ActionPerformed


    public void adicionarCliente() {
        Cliente cliente = new Cliente();
        FilaAtendimento fa = CaixaAtendimento.getFila();
        fa.addCliente(cliente);
    }

    public static void esvaziarCaixa(Integer id) {
        System.out.println("vou esvaziar a caixa " + id);
        if (id == 0) {
        System.out.println("entrei em esvaziar caixa");
            caixaAtendimento0.setBackground(new Color(0, 255, 0));
            caixaAtendimento0.setText("Caixa livre");
        } else if (id == 1) {
            System.out.println("entrei em esvaziar caixa");
            caixaAtendimento1.setBackground(new Color(0, 255, 0));
            caixaAtendimento1.setText("Caixa livre");
        } else if (id == 2) {
            System.out.println("entrei em esvaziar caixa");
            caixaAtendimento2.setBackground(new Color(0, 255, 0));
            caixaAtendimento2.setText("Caixa livre");
        }
    }

    public static void atualizarClientes() {
        fila1.setText("");
        fila2.setText("");
        fila3.setText("");

        Cliente cliente = new Cliente();
        FilaAtendimento fa = CaixaAtendimento.getFila();
        String pedido = "";
        Integer i = 0;
        Integer j = 0;
        for(Cliente c : fa.getFila()){
            i++;
            HashSet<ItemPedido> itensPedido = c.getPedido().getItem();
            for (ItemPedido item : itensPedido) {
                String produto = item.getProduto().getNome();
                Integer quantidade = item.getQuantidade();
                pedido += produto+ " - " + quantidade + "\n";
            }
            if (i == 1) {
                j++;
                fila1.setText(pedido);
            } else if (i == 2) {
                j++;
                fila2.setText(pedido);
            } else if ( i == 3 ) {
                j++;
                fila3.setText(pedido);
            }
            pedido = "";
        }
        String s = String.valueOf(fa.getFila().size() - j);
        clientesRestantes.setText(s);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea caixaAtendimento0;
    public static javax.swing.JTextArea caixaAtendimento1;
    public static javax.swing.JTextArea caixaAtendimento2;
    public static javax.swing.JTextArea caixaPagamento0;
    public static javax.swing.JTextArea caixaPagamento1;
    public static javax.swing.JTextArea caixaPagamento2;
    public static javax.swing.JLabel clientesRestantes;
    public static javax.swing.JTextArea fila1;
    public static javax.swing.JTextArea fila2;
    public static javax.swing.JTextArea fila3;
    public static javax.swing.JTextArea fila4;
    public static javax.swing.JTextArea fila5;
    public static javax.swing.JTextArea fila6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables

}
