/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSimulacao.java
 *
 * Created on Dec 7, 2009, 4:48:46 AM
 */

package br.ufrj.dcc.so20092.fastfood.view;

import br.ufrj.dcc.so20092.fastfood.model.CaixaAtendimento;
import br.ufrj.dcc.so20092.fastfood.model.Cliente;
import br.ufrj.dcc.so20092.fastfood.model.FilaAtendimento;
import br.ufrj.dcc.so20092.fastfood.model.ItemPedido;
import br.ufrj.dcc.so20092.fastfood.model.ItemPedido;
import java.awt.Color;
import java.util.HashSet;

/**
 *
 * @author kaiser
 */
public class PanelSimulacao extends javax.swing.JPanel {

    /** Creates new form PanelSimulacao */
    public PanelSimulacao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        caixaAtendimento0 = new javax.swing.JTextArea();
        clientesRestantes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        caixaAtendimento1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        caixaAtendimento2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        fila1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        fila3 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        fila2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        caixaAtendimento0.setColumns(20);
        caixaAtendimento0.setRows(5);
        caixaAtendimento0.setText("Caixa livre");
        jScrollPane9.setViewportView(caixaAtendimento0);

        clientesRestantes.setText("0");

        caixaAtendimento1.setColumns(20);
        caixaAtendimento1.setRows(5);
        caixaAtendimento1.setText("Caixa livre");
        jScrollPane5.setViewportView(caixaAtendimento1);

        caixaAtendimento2.setColumns(20);
        caixaAtendimento2.setRows(5);
        caixaAtendimento2.setText("Caixa livre");
        jScrollPane4.setViewportView(caixaAtendimento2);

        jLabel1.setText("Caixa Atendimento 0");

        jLabel2.setText("Caixa Atendimento 1");

        jLabel3.setText("Caixa Atendimento 2");

        jButton1.setText("Adicionar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fila1.setColumns(20);
        fila1.setRows(5);
        jScrollPane6.setViewportView(fila1);

        jLabel4.setText("Fila");

        jLabel5.setText("clientes restantes na fila");

        fila3.setColumns(20);
        fila3.setRows(5);
        jScrollPane8.setViewportView(fila3);

        fila2.setColumns(20);
        fila2.setRows(5);
        jScrollPane7.setViewportView(fila2);

        jLabel6.setText("ATENDIMENTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(11, 11, 11)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2))
                                            .addGap(12, 12, 12))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(130, 130, 130)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(clientesRestantes)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel5))
                                        .addComponent(jButton1))))))
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(clientesRestantes)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addGap(7, 7, 7)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atualizarClientes();
        adicionarCliente();
}//GEN-LAST:event_jButton1ActionPerformed


    public void adicionarCliente() {
        Cliente cliente = new Cliente();
        FilaAtendimento fa = CaixaAtendimento.getFila();
        fa.addCliente(cliente);
    }

    public static void esvaziarCaixa(Integer id) {
        System.out.println("vou esvaziar a caixa " + id);
        if (id == 0) {
        System.out.println("entrei em esvaziar caixa");
            caixaAtendimento0.setBackground(new Color(0, 255, 0));
            caixaAtendimento0.setText("Caixa livre");
        } else if (id == 1) {
            System.out.println("entrei em esvaziar caixa");
            caixaAtendimento1.setBackground(new Color(0, 255, 0));
            caixaAtendimento1.setText("Caixa livre");
        } else if (id == 2) {
            System.out.println("entrei em esvaziar caixa");
            caixaAtendimento2.setBackground(new Color(0, 255, 0));
            caixaAtendimento2.setText("Caixa livre");
        }
    }

    public static void atualizarClientes() {
        fila1.setText("");
        fila2.setText("");
        fila3.setText("");

        Cliente cliente = new Cliente();
        FilaAtendimento fa = CaixaAtendimento.getFila();
        String pedido = "";
        Integer i = 0;
        Integer j = 0;
        for(Cliente c : fa.getFila()){
            i++;
            HashSet<ItemPedido> itensPedido = c.getPedido().getItem();
            for (ItemPedido item : itensPedido) {
                String produto = item.getProduto().getNome();
                Integer quantidade = item.getQuantidade();
                pedido += produto+ " - " + quantidade + "\n";
            }
            if (i == 1) {
                j++;
                fila1.setText(pedido);
            } else if (i == 2) {
                j++;
                fila2.setText(pedido);
            } else if ( i == 3 ) {
                j++;
                fila3.setText(pedido);
            }
            pedido = "";
        }
        String s = String.valueOf(fa.getFila().size() - j);
        clientesRestantes.setText(s);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea caixaAtendimento0;
    public static javax.swing.JTextArea caixaAtendimento1;
    public static javax.swing.JTextArea caixaAtendimento2;
    public static javax.swing.JLabel clientesRestantes;
    public static javax.swing.JTextArea fila1;
    public static javax.swing.JTextArea fila2;
    public static javax.swing.JTextArea fila3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables

}
